[package]
name = "summarize-url"
version = "0.0.1"
authors = ["Joslin, Brady W (Brady) <brady@bradyjoslin.com>"]
edition = "2018"

[dependencies]
structopt = "0.3"
assert_cmd = "2.0.4"
algorithmia = "3.0.0-beta.3"