name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_on_ubuntu:

    runs-on: ubuntu-latest
    env:
      ALGO_KEY: ${{ secrets.ALGO_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build_on_mac:
    
    runs-on: macos-latest
    env:
      ALGO_KEY: ${{ secrets.ALGO_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build_on_windows:
    
    runs-on: windows-latest
    env:
      ALGO_KEY: ${{ secrets.ALGO_KEY }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
